[tool.poetry]
name = "air-rag"
version = "0.1.0"
description = ""
authors = ["Prashant Srivastava"]
readme = "README.md"
packages = [{include = "biokb"}]

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
